[package]
name = "crabbers"
version = "0.0.1"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
strum = "0.26.3"
color-eyre = "0.6.3"
clap = "4.5.21"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"